#!/bin/bash
# clean.sh - Reverts the workspace to its initial state by removing all generated artifacts

set -e

PROJECT_ROOT="$(pwd)"

echo "=== Cleaning Workspace Artifacts ==="

echo "1. Removing Python virtual environment..."
rm -rf "$PROJECT_ROOT/.venv"

echo "2. Removing OpenClaw installation and configurations..."
rm -rf "$PROJECT_ROOT/.openclaw"

echo "3. Removing Root Node Modules..."
rm -rf "$PROJECT_ROOT/node_modules"
rm -f "$PROJECT_ROOT/package-lock.json"

echo "4. Cleaning Booksim compilation files..."
if [ -d "$PROJECT_ROOT/booksim/src" ]; then
    # Run make clean if the Makefile exists
    (cd "$PROJECT_ROOT/booksim/src" && make clean 2>/dev/null || true)
fi

echo "5. Cleaning Plugin artifacts..."
rm -rf "$PROJECT_ROOT/plugins/tool-approval/node_modules"
rm -rf "$PROJECT_ROOT/plugins/tool-approval/dist"
rm -rf "$PROJECT_ROOT/plugins/file-preview/node_modules"
rm -rf "$PROJECT_ROOT/plugins/file-preview/dist"

echo "6. Cleaning Frontend artifacts..."
rm -rf "$PROJECT_ROOT/platform/frontend/bookin/node_modules"
rm -rf "$PROJECT_ROOT/platform/frontend/bookin/dist"
rm -rf "$PROJECT_ROOT/platform/frontend/bookin/.next" 2>/dev/null || true # In case it's a Next.js app

echo "7. Cleaning Backend artifacts..."
# Remove Python pycache directories
find "$PROJECT_ROOT" -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true

echo "=== Clean Complete ==="
echo ""
echo "Note: This script removed all explicitly known artifacts generated by setup.sh and run.sh."
echo "If you want to perform a STRICT revert to the latest git commit (WARNING: This will delete ALL untracked files, including uncommitted work), you can run:"
echo "  git clean -fdx"
